import { Clients } from "components";
import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MERN With GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Clients />
    </div>
  );
};

export default Home;
