import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { gql } from "@apollo/client";

//
import client from "apollo-client";

// interface Clients{
//   id?: boolean;
//   name?:string;
//   email?:string;
//   phone?:string;
// }

const Home: NextPage = () => {
  // console.log(clients)
  return (
    <div>
      <Head>
        <title>MERN With GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;

// export async function getServerSideProps() {
//   const { data } = await client.query({
//     query: gql`
//       query Clients {
//         clients {
//           id
//           name
//           email
//           phone
//         }
//       }
//     `,
//   });

//   return {
//     props: {
//       clients: data.clients,
//     },
//   };
// }
